name: .muheqa
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip=21.3.1
  - python=3.8
  - absl-py
  - astunparse
  - clang
  - flatbuffers
  - gast
  - google-pasta
  - grpcio
  - h5py
  - keras
  - keras-preprocessing
  - numpy
  - opt_einsum
  - protobuf
  - six
  - tensorboard
  - tensorflow-estimator
  - termcolor
  - typing-extensions
  - wrapt
